pipeline{
    agent any
    tools{
        maven "maven"
    }
    stages{
        stage("Build JAR File"){
            steps{
                checkout scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[credentialsId: 'github_jenkins', url: 'https://github.com/cristowo/Tingeso_Evaluacion_1']])
                dir("Tingeso1"){
                    bat "mvn clean install"
                }
            }
        }
        stage("Test"){
            steps{
                dir("Tingeso1"){
                    bat "mvn test"
                }
            }
        }
        stage("SonarQube Analysis"){
            steps{
                dir("Tingeso1"){
                    bat "mvn clean verify sonar:sonar -Dsonar.projectKey=tingeso1_sonar -Dsonar.host.url=http://localhost:9000 -Dsonar.login=sqp_51e8272f6f9b7f87afeffb035adf26140281e9d1"
                }
            }
        }
        stage("Build Docker Image"){
            steps{
                dir("Tingeso1"){
                    bat "docker build -t cristowo/docker_tingeso1 ."
                }
            }
        }
        stage("Push Docker Image"){
            steps{
                dir("Tingeso1"){
                    withCredentials([string(credentialsId: 'dockerpass', variable: 'dckpass')]){
                        bat "docker login -u cristowo -p ${dckpass}"
                        
                    }
                    bat "docker push cristowo/docker_tingeso1"
                    
                }
                
            }
        }
    }
    post{
        always{
            dir("Tingeso1"){
                bat "docker logout"
            }
        }
    }
}